export enum IpcEvents {
  NEW_BROWSER_TAB = 'NEW_BROWSER_TAB',
  RELOAD_BROWSER_TAB = 'RELOAD_BROWSER_TAB',
  STOP_BROWSER_TAB = 'STOP_BROWSER_TAB',
  SET_MENU_ITEM_OPTIONS = 'SET_MENU_ITEM_OPTIONS',
  MONACO_TOGGLE_OPTION = 'MONACO_TOGGLE_OPTION',
  TOGGLE_DEV_TOOLS = 'TOGGLE_DEV_TOOLS',
  RELOAD_WINDOW = 'RELOAD_WINDOW',
  SELECT_ALL_IN_EDITOR = 'SELECT_ALL_IN_EDITOR',
  GET_STORE_VALUE = 'GET_STORE_VALUE',
  SET_STORE_VALUE = 'SET_STORE_VALUE',
  SAVE_USER_FILE = 'SAVE_USER_FILE',
  LOAD_USER_FILE = 'LOAD_USER_FILE',
  OPEN_SETTINGS = 'OPEN_SETTINGS',
  WEBCONTENTS_READY_FOR_IPC_SIGNAL = 'WEBCONTENTS_READY_FOR_IPC_SIGNAL',
}

export const ipcMainEvents = [
  IpcEvents.RELOAD_WINDOW,
  IpcEvents.SET_MENU_ITEM_OPTIONS,
  IpcEvents.GET_STORE_VALUE,
  IpcEvents.SET_STORE_VALUE,
  IpcEvents.SAVE_USER_FILE,
  IpcEvents.LOAD_USER_FILE,
];

export const ipcRendererEvents = [
  IpcEvents.NEW_BROWSER_TAB,
  IpcEvents.RELOAD_BROWSER_TAB,
  IpcEvents.STOP_BROWSER_TAB,
  IpcEvents.MONACO_TOGGLE_OPTION,
  IpcEvents.TOGGLE_DEV_TOOLS,
  IpcEvents.SELECT_ALL_IN_EDITOR,
  IpcEvents.OPEN_SETTINGS,
];
